### ISSUE TITLE
Load templates from plugin

### ISSUE THREAD

**Issue by MorganAkki** [themosis/plugin#13]
Hello,

I would like to know how can I use templates from a custom plugin. I have a templates.config.php with the right prefix in resources/config but I don't know how to load it. 
In the documentation we can find this line, but where can I use it ? 
`$templates = Config::get('com_domain_shop_templates');`

Thank you !

**Comment by jlambe** [comment]
Normally the plugin boilerplate is setup to load your plugin configuration files. The issue here is that you can't call your file `templates.config.php` as it is going to conflict with the one set into the theme.

When setting up the plugin, a "namespace" must be defined to avoid file conflicts (not talking about a PHP namespace here). For example: `com_example_shop` is a valid namespace string. So based on that, your configuration file name should be: `com_example_shop_templates.config.php` and you can then retrieve the information like so:
```php
$templates = Config::get('com_example_shop_templates');
```

**Comment by jlambe** [comment]
Hmm as explained, the boilerplate is configured to bootstrap your configuration file. See code line here: https://github.com/themosis/plugin/blob/ae38b46f6b7b766ef4efff6c67a9eda417ba3053/plugin-name.php#L82

Perhaps verify your path or did you correctly setup these lines (namespace): https://github.com/themosis/plugin/blob/ae38b46f6b7b766ef4efff6c67a9eda417ba3053/plugin-name.php#L45

**Comment by MorganAkki** [comment]
Sorry for english people but it will be easier for me to answer in french...

En fait, tous mes autres fichiers de config sont bien pris en compte. Il n'y a vraiment que le templates.config qui n'est pas chargé d'après moi. Mon plugin se nomme **akki-elasticsearch**, j'ai bien mon tableau : 
```
$vars = [
    'slug' => 'akki-elasticsearch',
    'name' => 'Akki Elasticsearch',
    'namespace' => 'com.akki.elasticsearch',
    'config' => 'com_akki_elasticsearch',
];
```
Dans mon répertoire "resources->config" j'ai les fichiers suivants : 
- com_akki_elasticsearch_loading.config.php
- com_akki_elasticsearch_providers.config.php
- com_akki_elasticsearch_templates.config.php

En suivant juste la doc je n'ai pas réussi à faire en sorte que mon template soit visible en back-office.
J'ai réussi à l'activer en ajouter les lignes suivantes dans le .php à la racine de mon plugin : 

```
$theme = container();
$templates_config = Config::get('com_akki_elasticsearch_templates');
$templates = new Themosis\Config\Template($templates_config, $theme['filter']);
$templates->make();

```

Est-ce le comportement normal ? Car effectivement je pensais que mon fichier config concernant les templates serait pris en compte automatiquement.

**Comment by jlambe** [comment]
Non effectivement, créer un fichier de configuration `..._templates.config.php` ne génère pas automatiquement le chargement de ces templates .

Le code ajouté dernièrement dans ton exemple est correct et il doit bien être ajouté dans le fichier racine de ton extension.

**Comment by MorganAkki** [comment]
Je te remercie et désolé pour le manque de clarté dans ma question initiale.
