### ISSUE TITLE
Don't see my plugin in Dashboard

### ISSUE THREAD

**Issue by Neidra** [themosis/plugin#14]
Hey,

I create already create a first plugin and he is functional. But my second one isn't displayed in my Dashboard (plugins.php).
Someone could help me?

**Comment by Jaspervv** [comment]
That's odd, it should show on the WordPress plugins page after cloning/copying the boilerplate.

The bare minimum a plugin needs to be shown, is it's own folder inside your `./htdocs/content/plugins/`
And a php file inside it containing the plugin name.

Example:
![screenshot from 2018-12-17 10-10-25](https://user-images.githubusercontent.com/35364310/50077248-2798b000-01e4-11e9-9ef4-ed43bcad43b2.png)

Plugins page:
![screenshot from 2018-12-17 10-12-56](https://user-images.githubusercontent.com/35364310/50077326-5d3d9900-01e4-11e9-98b1-4b8609917180.png)
