### ISSUE TITLE
cant use blade theme engine

### ISSUE THREAD

**Issue by mobin733** [themosis/plugin#15]
Hello! 
when i create sample.blade.php in views folder this happen:
`Warning: file_put_contents(\views\/c450af0719ef.........2d027adb895b.php): failed to open stream: No such file or directory in ...\wp-content\plugins\framework\vendor\illuminate\filesystem\Filesystem.php on line 122`

sample.php and sample.twig is working

**Comment by jlambe** [comment]
Hi, you're missing a `storage/views` directory at your project root. Try to add those folders so templates engines can store compiled views.
