### ISSUE TITLE
Themosis 2.0 plugin autoloader

### ISSUE THREAD

**Issue by TipyTechnique** [themosis/plugin#16]
Hi,

I'm trying your new plugin's boilerplate in themosis 2.0, but files on the resources folder are not autoloaded.

How i must change the plugin's files ? Documentation for plugins is not updated.

Thank you !

**Comment by jlambe** [comment]
The structure of the theme and plugin has changed. The `resources` directory is a namespaced directory and is only holding your php classes.

The old `admin` directory is now the `inc` (for includes) folder where all files will be auto included and you can nest folders as well.

Regarding assets, both use Laravel Mix so you can edit the webpack.mix.js file at plugin and theme root. Assets should compile to the `dist` directory.

Hope this help you to get started. Documentation is coming soon for theme and plugin.

**Comment by jlambe** [comment]
Plugin documentation has been updated: https://framework.themosis.com/docs/2.0/plugin/
