### ISSUE TITLE
[Question] Using a plugin in an existing Wordpress installation? 

### ISSUE THREAD

**Issue by eleftrik** [themosis/plugin#19]
Is it possible to use a Themosis generated plugin in an existing standard Wordpress installation? 

Thank you

**Comment by jlambe** [comment]
No it's not possible as your plugin will need dependencies from the core package to work. The plugin boilerplate is developed to extend WordPress only on a themosis stack.

**Comment by eleftrik** [comment]
As I imagined :-(  Any possible "hack"? For example, including dependencies from the core package inside the plugin's `composer.json`?

**Comment by jlambe** [comment]
There is probably a way but I won't personnaly invest on this as it will bring the same issues WordPress plugin developers are doing: provide the same dependencies multiple times at runtime using composer inside a plugin.

**Comment by eleftrik** [comment]
Your point of view is unexceptionable.
Thanks for the clarifications.
