### ISSUE TITLE
Plugin Boilerplate

### ISSUE THREAD

**Issue by thiagof** [themosis/plugin#2]
Hi,

I have put together the boilerplate for a plugin. If you wish a PR, please let me know:

https://github.com/thiagof/themosis-plugin

**Comment by jlambe** [comment]
Hi,

I will take a deeper look later but as a first notice, don't put your code inside the `app` directory inside the plugin. Use a folder name of `resources`. Check the current master branch from the `themosis/framework` and `themosis/theme` repositories for API changes as a lot is changing in release 1.2.0. as well.

**Comment by thiagof** [comment]
Have done a review in the master theme. Published some changes into 1.2.0 branch of that repository.

Do you recommend using branch master for the framework?
