### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zgelici** [themosis/plugin#4]
I installed the latest wordpress and get the next error:

Fatal error: Call to undefined function container() in /var/www/html/wpp/htdocs/content/plugins/name/plugin-name.php on line 81
Unhandled Exception

Message:

Call to undefined function container()
Location:

/var/www/html/wpp/htdocs/content/plugins/name/plugin-name.php on line 81

**Comment by jlambe** [comment]
You can't use the plugin with version 1.2.3. Only with the next release coming Tuesday.

**Comment by zgelici** [comment]
Thanks :)
